dist: trusty
sudo: false
language: java

cache:
 directories:
   - $HOME/.cache

jdk:
  - oraclejdk8

env:
  global:
    # CLOUDSMITH_API_KEY=foo
    - secure: KYw1EMAufTaIaBzvG5Y7F7sPjeow0Dr1cn84qmqqY5QPwSrYGS0gaaNyZp90NtTvU7/CA09lDXLUaQWlKrJUIk+nyaBQZDCQS9Ir5sU3oVocifJxZJrq8/fueNTSfq8/+xdsFYlCb4QEVX74luPavb74sJWDboC7/TF5raFAtW/u8w/zQpd6yEDLoQgW2JMM61qq106Y4CWEwq4DRDTpvWmv0Z2f+vXIw2Zo20xeDlb0TTCl+2htGrM02j0GkaNUfxkvEL/AcR/4TCoosSgkVM6e+GUqHyeexIaZg0w6TZUQWLOsubekr9u9b5ItgDwk3804x9EFxnleDl5Twb1ksLgj+HUL7gqE6bV/gICd5Q9gI76uh41gwVzZk3NyeWGKrhocDFI3DQTpQG4LdPsysuZUzY+GRfhbXVinC69+oseNO5tQ49g9Onaj3VKsQsYFYHhHfxGqbTtWZSJQWJcT31aNZ4bvoFjTbpK2C2LdL4warfdQRUttQo9WNAvfEloJKhZMxG9Z5RAV9Cdsxg228YzuKnBWzo46KYErxzxFs+MYpsGu4wQomYRTYVjPbSiH8LmAveZmCdcVUrMz5INH/oaa2axQTF2jyRGpYCu9FCVsJmPVC6TG7TKRzymCfP1RtNlUFhRQYlEDtC/uKS7N6naqpwNk3ja+DA1XQGbdw8w=

script:
  - set -e
  - ./scripts/build.sh
  - ./scripts/test.sh

before_deploy:
  - pyenv global 2.7
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade wheel
  - pip install cloudsmith-cli twine

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ZPDS9f4qlpQoQpHc6zEBKJR69ZVR25b2UwSyvfGzrJgIddXP9aQg6uSi9U/ZFgZatAUThaKBq2o9tzsMdkg4BCx+TQZAAAZpqJ/E62QFgFm7WkIumz2HoZ4OR+NNuY/BJQLXsXQe9H9p2NoW2EUH+PnXHkEaxMNzx6gQeNYObcPkF69SVZDtgNPq/svKOo9HxQmDmD4sJyHchlA2bpBPYcZQRaxCBYbLdA1CUyDhbvRWP/ZFsSpk/g6ylP6cFjUp+DZAl9jObgDeFqczLVmaf05h5KSRaTtX4n8gOPss6rHCb57clU1JR3ZrxVBg5Uj1JakF8kBxOIeWUQ0QkcyRhnel4n2kDKWYRm+DKdRJioCxT0cHQFh6o1LKxAr0ogpAY8JhXPTqdnhwNsVzcSvZlfTlhlhjGGi5bJ5avwXVLbLv73/OXKE/xmfYIA2Csn5AHbYkJ5ZD/WYXnd4xgfShRUUsL6+vZUhI/vgmPOtwXBP0FkEPW/vb1PbJVr/ASb3YKPH0doaeMZvIkxS3Fx/hwidrMvzdsFjYgWepKUmCAQ/eqdYQMBrIPIyskZXQijN06iHNkfGGZ4gWEAZHPjO2xNwodNGopzrj5jzMy3iH3hmGdjviW8TH+j3Kwv/nb9kjarQSLd56mupQ/Rw9wHcaBoXdpheJ66uB1mbhAeD5VkU=
    file_glob: true
    file: target/cloudsmith-maven-wagon-*.jar
    on:
      tags: true

notifications:
  email:
    on_failure: always
    on_success: change
  slack:
    secure: qm4pgQYyTwTAkH0jTJxwMnvkWDhXEbulGRZUbMZbq2kvDAgnfWmusuvWNw0iGl9ArWpzgJxKKg1+hElKSuLgtTo4YGn78LoqhRTdZdNOSr+4/C8JRFeBZJMJUUqVzqWWdojuX5HogEjR6SmH+sr5KQkGJKaFanWNETQ8aaRSj1omt0dcLRoFQVNd2CXwo6qwRY/8r+a5sLBtOwSY/wtoTnBT6ebtNWctsyYmBClbJsUXlXlwRK7npDFz6S2f+6/0yiXoACz5XZLkwghMsX465rSMep9LVcFARAyZide2b+nkSqPdyFje4T7APhEWNCtXHg1AJSHw3KsQEXmnifJFdgRfTu8v7vM1dnBlTdXaRpavHJOVS0TEIvKdd5vmemNMPVVVMbTcQXwxSkl8oSacGjO8vbK91WGTJI3psoUKp7EP0MYeq9TAZpoZJHpemPg7H5fZdA5UyBFROaU7gsNb96JUDuGQAm+7AmrYx1YFqTjFioHtVF1XPs4elgkHEu1+D6kq9doKMQ+M38yIj1KkRtLjuEFKZ286joeoCrisPaFgsPsAHG46q1pqtIoXjQZKAwIvMbB1K7OuK5KO4oY+ppOZPZi56HLVh6oLzK4T6JA64JBIUo77dzOFO0hy/0riH6iEaOpG4hkt4f1sVBpGyTQxTpY/6Yzf8gQ2oJUvo3M=
